### ISSUE TITLE
1.8.4: PHP Fatal error when loading any page (ex. /page/648/)

### ISSUE THREAD

**Issue by janvitos** [keycdn/cache-enabler#293]
Hi,

Since I've installed Cache Enabler 1.8.4, I'm getting tons of critial errors in my webserver error log. Those errors are being generated when accessing any page on my website (ex. /page/648/).

Here is the error: 

`PHP Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0`

I've tried accessing a page myself, and I get a 500 error in Chrome. It seems the error is triggered when the page is being accessed for the first time before it has been cached. If I refresh the page, it loads properly.

Reverting back to 1.7.2 fixes the issue.

Thanks.

**Comment by coreykn** [comment]
This occurs on a fresh install of 1.8.4 (without any hooks)? If yes, then it sounds like Cache Enabler is conflicting with how another plugin is starting an output buffer. If you have an idea on which plugin this could be then you could try deactivating it to see, otherwise can you send a list of the plugins installed on your site?

This can either be your Site Health Info or a screenshot of the plugins page. (Feel free to share any information privately, like your Site Health Info, through our [contact form](https://www.keycdn.com/contact) if you'd prefer.)

**Comment by janvitos** [comment]
Hi,

Yes, this occurs on a fresh install of 1.8.4 without any hooks.

I might have found the issue. It seems it could be related to a ob_start() function I had lying around in an old and unused functions file. After removing this unused file from includes and upgrading to 1.8.4 again, I am not seeing the error anymore. But I will run the site for another 24h before closing this ticket.

**Comment by coreykn** [comment]
Thanks for the additional information. That sounds like that would be the cause of the issue, but I'll be available if you need any additional help troubleshooting it.

**Comment by janvitos** [comment]
Seems like the problem is fixed.

I will close this ticket.

**Comment by janvitos** [comment]
Seems like the issue came back and it is intermittent, so it might be hard to diagnose.

I also noticed the issue doesn't only occur on pages, it occurs on articles as well.

I will come back later with more details.

**Comment by janvitos** [comment]
Here's the list of active plugins you had requested:

Ad Inserter
Cache Enabler
Cloudflare
Disable Emojis (GDPR friendly)
Disable Gutenberg
JSM's Non-Breaking Space for French Content
Media Cleaner
Media Credit
OneSignal Push Notifications
Query Monitor
Schema & Structured Data for WP & AMP
The SEO Framework
WP Crontrol
WP Mail SMTP
WP-Optimize - Clean, Compress, Cache
XML Sitemap & Google News

But I want to reiterate that everything works perfectly fine with all these plugins active and Cache Enabler 1.7.2. So really, there seems to be an issue / conflict with 1.8.4 and buffering.

**Comment by janvitos** [comment]
I have found and removed the last instance of ob_start() in a custom functions file that was being called with the template_redirect action.

I will see how it goes and post an update in 24-48 hours.

**Comment by janvitos** [comment]
So I started getting the errors again today. I am really not sure where to look next.

There are no more ob_start() functions called in my own theme, so it must be a conflict with a plugin.

Here is the list of active plugins on my website:

```
Ad Inserter
Cache Enabler
Cloudflare
Disable Emojis (GDPR friendly)
Disable Gutenberg
JSM's Non-Breaking Space for French Content
Media Cleaner
Media Credit
OneSignal Push Notifications
Query Monitor
Schema & Structured Data for WP & AMP
The SEO Framework
WP Crontrol
WP Mail SMTP
WP-Optimize - Clean, Compress, Cache
XML Sitemap & Google News
```

Thanks.

**Comment by coreykn** [comment]
To confirm, the same PHP error as posted in your first response? The output buffering did not change in the 1.8 branch.

Have any new plugins been added or any existing plugins been updated recently? Is the page caching disabled in the WP-Optimize plugin?

**Comment by janvitos** [comment]
Yes, it is the same exact error as in the first response.

No new plugins have been added. Page caching is disabled in WP-Optimize. Actually, this plugin is deactivated all the time. I only activate it when I need to optimize my website.

To confirm the issue only exists in 1.8.4 and NOT in 1.7.2, I have reinstalled 1.7.2 and got 2 new articles posted, and there were no errors at all.

**Comment by janvitos** [comment]
After looking at the diff from 1.7.2 to 1.8.4, I see these 2 lines that have been modified in relation to buffering:

This line in advanced-cache.php:

`if ( ! $cache_enabler_cache_delivered ) {`

Has been replaced by this line:

`if ( Cache_Enabler_Engine::start() && ! Cache_Enabler_Engine::deliver_cache() ) {`

Do you think this could be related to the issue?

**Comment by coreykn** [comment]
Thanks for the additional information. I'm unable to replicate the error when publishing new posts on a fresh install of WordPress 5.8.1 and Cache Enabler 1.8.4. The logic for starting the output buffering didn't change in the `advanced-cache.php` file in the 1.8 branch. It's just no longer assigning the value to a variable as it did before. The cache engine won't start early in the backend, which means the output buffering for Cache Enabler is only started when on frontend pages. That means I don't think the error is related to Cache Enabler if you're experiencing this error when saving posts in the backend.

Furthermore, we haven't had any other reports of this error yet. That typically indicates it's an issue related to your install in particular. Can you please check all of your custom functionality in more detail? I'd be happy to take a look at these files if you'd like to provide them, either here or through our contact form previously shared. Alternatively, try deactivating your plugins one by one and then try to replicate the issue.

**Comment by janvitos** [comment]
I understand that the logic for starting the output buffering didn't change, but something must've changed since I am now getting this error in the new version and not in the old one.

The fact that you didn't have any reports yet doesn't indicate that the issue isn't widespread. It's not a showstopper. But I do see error 500 here and there pop-up in the error log. So users are getting them. Bots are getting them. But it's not on every page load. And as I've stated before, after the page has triggered the error, it loads normally for subsequent visits. So it seems it is triggered right when the page is being cached, hence the reason why it is related to buffering.

We have checked our custom functions and made sure there are no traces left of ob_start() or any kind of buffering. But this shouldn't matter anyways. We should be able to use buffering with other plugins. Many other plugins use buffering and we've never had issues with our own custom buffering.

**Comment by janvitos** [comment]
I can actually now trigger the issue easily. Here are the steps:

1. Update an article so it clears the cache
2. Access the article or any related pages with a guest browser where I am NOT logged into Wordpress
3. Browser gives error 500
4. The following 2 errors are logged in the NGINX log:

```
2021/09/10 20:45:28 [error] 906753#906753: *717337 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /***/wp-includes/class-wp-term.php on line 198" while reading response header from upstream, client: ***.***.***.***, server: www.***.com, request: "GET /***/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "www.***.com", referrer: "https://www.***.com/page/2/"
2021/09/10 20:45:28 [error] 906753#906753: *717337 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0" while reading upstream, client: ***.***.***.***, server: www.***.com, request: "GET /***/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "www.***.com", referrer: "https://www.***.com/page/2/"
```

**Comment by janvitos** [comment]
So I decided to reboot my web server to clear all types of cache.

For the time being, I am NOT able to reproduce the issue anymore.

We'll see how it goes for the next 24-48 hours.

If the issue is fixed, there might've been an issue with the new version and the object cache which was cleared when the server was rebooted.

I will keep this ticket updated.

**Comment by denathor** [comment]
I am having the same issue as above, random server 500 errors after updating to 1.8.4
[Sun Sep 12 15:23:17.644722 2021] [php7:error] [pid 1410] [client 52.90.83.110:53928] PHP Fatal error: Uncaught Error: Call to undefined function wp_opcache_invalidate() in /nas/content/live/stagingdx/wp-content/plugins/cache-enabler/inc/cache_enabler_disk.class.php:1044\nStack trace:\n#0 /nas/content/live/stagingdx/wp-content/plugins/cache-enabler/inc/cache_enabler_engine.class.php(88): Cache_Enabler_Disk::get_settings(true)\n#1 /nas/content/live/stagingdx/wp-content/plugins/cache-enabler/inc/cache_enabler_engine.class.php(26): Cache_Enabler_Engine->__construct()\n#2 /nas/content/live/stagingdx/wp-includes/class-wp-hook.php(303): Cache_Enabler_Engine::start('')\n#3 /nas/content/live/stagingdx/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)\n#4 /nas/content/live/stagingdx/wp-includes/plugin.php(470): WP_Hook->do_action(Array)\n#5 /nas/content/live/stagingdx/wp-settings.php(578): do_action('init')\n#6 /nas/content/live/stagingdx/wp-config.php(125): require_once('/nas/content/li...')\n#7 /nas/content/live/stagingdx/wp-load.php(50): require_once('/nas/content/li...')\n#8 /nas/content/live/stagingdx/ in /nas/content/live/stagingdx/wp-content/plugins/cache-enabler/inc/cache_enabler_disk.class.php on line 1044

**Comment by janvitos** [comment]
Hi @denathor!

Although your issue seems to generate error 500 like mine, it is quite different from the one I am experiencing according to the error log you've posted. So I think you're better off opening your own ticket so your issue can be addressed separately and get the proper support it deserves.

**Comment by denathor** [comment]
Ok, thank you

**Comment by janvitos** [comment]
Hi @coreykn,

I took this screenshot of my web server analytics that shows errors with 1.8.4 and 1.7.2.

[](https://imgur.com/a/0wVx4Kr)

As you can see, before September 11th (red line), there were many errors in the error log with 1.8.4. But after switching to 1.7.2, the errors completely disappeared.

**Comment by coreykn** [comment]
@janvitos, to troubleshoot this further, does the same error occur if you increase your server and/or application memory limit (e.g. something like `1024M` with a max of `2048M`)?

**Comment by janvitos** [comment]
Hey @coreykn,

I have already tried this and the same error occurs (but after a bit more time of hanging).

**Comment by coreykn** [comment]
Hmm, can you send over your Site Health Info and all extensions added to Cache Enabler? That would be any custom behavior added to Cache Enabler. If you have other custom behavior related to the WordPress core that'd be helpful to have as well. The extensions can be shared through a site like Pastebin, or if you'd prefer to attach file(s) that can be done in a reply. That will help me create a similar environment so I can replicate the error.

**Comment by coreykn** [comment]
Thanks. To help with what I'm working on, what did you set the `WP_MEMORY_LIMIT ` and `WP_MAX_MEMORY_LIMIT ` to when the issue continued for you? I'll be adding a new feature here shortly that should address the memory related issues for some installs. If you happen to have the time and are interested I'd love to have you test it before its release.

**Comment by janvitos** [comment]
Hi @coreykn,

Thanks for working on the issue.

I'm not sure I understand your question correctly about WP_MEMORY_LIMIT and WP_MAX_MEMORY_LIMIT. If you want to know what they are currently set at, they are unset in wp-config.php. I just use WordPress's default values. As per WordPress Site Health, WP_MEMORY_LIMIT is set at 128M and WP_MAX_MEMORY_LIMIT is set at 256M. When you asked me to test 1024M or 2048M, I set them both at 1024M. I can test again if this is what you want.

I would be glad to test your new version that addresses the memory issues. I am currently still using 1.7.2.
