### ISSUE TITLE
Fatal error: Call to a member function cache_size() on null

### ISSUE THREAD

**Issue by RavanH** [keycdn/cache-enabler#42]
Related thread on WP.org forums https://wordpress.org/support/topic/fatal-error-call-to-a-member-function-cache_size-on-null/

    [06-Nov-2018 15:13:17 UTC] PHP Fatal error:  Uncaught Error: Call to a member function cache_size() on null in /home/xxx/public_html/wp-content/plugins/cache-enabler/inc/cache_enabler.class.php:822
    Stack trace:
    #0 /home/xxx/public_html/wp-content/plugins/cache-enabler/inc/cache_enabler.class.php(789): Cache_Enabler::get_cache_size()
    #1 /home/xxx/public_html/wp-includes/class-wp-hook.php(286): Cache_Enabler::add_dashboard_count(Array)
    #2 /home/xxx/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
    #3 /home/xxx/public_html/wp-admin/includes/dashboard.php(316): apply_filters('dashboard_glanc...', Array)
    #4 /home/xxx/public_html/wp-admin/includes/template.php(1073): wp_dashboard_right_now('', Array)
    #5 /home/xxx/public_html/wp-admin/includes/dashboard.php(230): do_meta_boxes(Object(WP_Screen), 'normal', '')
    #6 /home/xxx/public_html/wp-admin/index.php(160): wp_dashboard()
    #7 {main}
      thrown in /home/xxx/public_html/wp-content/plugins/cache-enabler/inc/cache_enabler.class.php on line 822

seems to be happening on the admin dashboard.

**Comment by RavanH** [comment]
Occurs when Permalinks are not set.
